nome: Gerar dados

em:
  cronograma: # executar a cada 12 horas
    - cron: "* */12 * * *"
  workflow_dispatch:

empregos:
  construir:
    nome: Trabalhos para atualizar dados
    corre - em: ubuntu - mais recente
    passos:
      # Animação de serpente
      - usa: Platane / snk @ master
        id: cobra - gif
        com:
          github_user_name: imvitoriaf
          svg_out_path: dist / github - contribuição - grade - cobra.svg

      - usa: louco - máximo / ação - github - páginas @ v2.1.3
        com:
          target_branch: saída
          build_dir: dist
        env:
          GITHUB_TOKEN: Segredos $ { {. GITHUB_TOKEN } }
